apps/funcionarios/urls.py
from django.contrib import admin
from django.urls import path

from apps.funcionarios.views import FuncionarioListView, FuncionarioUpdateView, FuncionarioDeleteView, \
    FuncionarioCreateView, relatorio_funcionarios, PDF, PDFTemplateView

urlpatterns = [
    path('list_funcionarios/', FuncionarioListView.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioCreateView.as_view(), name='create_funcionarios'),
    path('editar/<int:pk>/', FuncionarioUpdateView.as_view(), name='edit_funcionarios'),
    path('deletar/<int:pk>/', FuncionarioDeleteView.as_view(), name='delete_funcionarios'),
    path('pdf-reportlab/', relatorio_funcionarios, name='pdf-reportlab'),
    path('pdf-xhtml2pdf/', PDF.as_view(), name='pdf-xtml2pdf'),
    path('pdf-xhtml2pdf-debug/', PDFTemplateView.as_view(), name='pdf-xtml2pdf-debug'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from apps.core.views import home, GroupViewSet, UserViewSet


from django.urls import include, path
from rest_framework import routers

from apps.funcionarios.api.viewsets import FuncionarioViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'api/funcionario', FuncionarioViewSet)
router.register(r'api/hora-extra', FuncionarioViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('departamentos/', include('apps.departamentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('', include('apps.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),

    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def __str__(self):
        return self.descricao

    def get_absolute_url(self):
        return reverse('edit_funcionarios', args=(self.pertence.id, ))

apps/funcionarios/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models import Sum
from django.urls import reverse

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=100, help_text='nome do funcionário')
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamento = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.nome

    @property
    def total_hora_extra(self):
        total = self.registrohoraextra_set.filter(utilizada=False).aggregate(soma_horaextra=Sum('horaextra'))['soma_horaextra']
        return total or 0

    def get_absolute_url(self):
        return reverse('list_funcionarios')

apps/registro_hora_extra/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horaextra = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def __str__(self):
        return self.motivo

    def get_absolute_url(self):
        return reverse('edit_funcionarios', args=(self.funcionario.id, ))

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, TemplateView
from xhtml2pdf import pisa

from apps.funcionarios.models import Funcionario

import io
from django.http import FileResponse
from reportlab.pdfgen import canvas


class FuncionarioListView(ListView):
    model = Funcionario

    # listar apenas funcionários da empresa
    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioUpdateView(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamento']


class FuncionarioDeleteView(DeleteView):
    model = Funcionario
    # retorna o url passado para reverse_lazy
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreateView(CreateView):
    model = Funcionario
    fields = ['nome', 'departamento']

    def form_valid(self, form):
        # criar funcionario e não comitar para o banco
        funcionario = form.save(commit=False)
        # criar empresa para funcionário
        funcionario.empresa = self.request.user.funcionario.empresa
        # criar usuário para funcionário
        username = " ".join(funcionario.nome.split(' ')[:2])
        funcionario.user = User.objects.create(username=username)
        # salvar funcionário
        funcionario.save()
        return super(FuncionarioCreateView, self).form_valid(form)


def relatorio_funcionarios(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'

    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()
    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(200, 810, "Hello world.")

    funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)
    y = 750

    for funcionario in funcionarios:
        str_ = f'NOME: {funcionario.nome} | HORAS: {funcionario.total_hora_extra}'
        p.drawString(50, y, str_)
        y -= 20

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response


class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(html.encode("UTF-8"), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type="application/pdf"
            )
            response['Content-Disposition'] = f'attachment; filename={filename}.pdf'
            return response
        else:
            return HttpResponse("ERROR", status=400)


class PDF(View):

    def get(self, request):
        params = {
            'hoje': 'variavel hoje',
            'vendas': 'variavel vendas',
            'request': request
        }
        return Render.render(path='funcionarios/relatorio.html', params=params, filename='relatorio_pdf.pdf')


class PDFTemplateView(TemplateView):
    template_name = 'funcionarios/relatorio.html'

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %}
    Lista de Funcionários
{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        <p> Você está certo de que quer deletar o funcionario {{ funcionario.nome }}</p>
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger"> Deletar </button>
    </form>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base/base.html' %}

{% load bootstrap %}


{% block title %}
    Lista de Funcionários
{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit"> Submit </button>
    </form>

{% if object %}
    <div class="container mt-4">

        <h3> Documentos </h3>
        <ul class="list-group">
            {% for documento in object.documento_set.all %}
                <li class="list-group-item">
                    <a href="{% url 'edit_documento' documento.id %}">{{ documento.descricao }}</a>
                </li>
            {% endfor %}
        </ul>
        <a class="btn btn-info" href="{% url 'create_documento' object.id %}"> Add Documento</a>

    </div>

    <div class="container mt-4">

        <h3> Hora Extra </h3>
        <ul class="list-group">
            {% for rhe in object.registrohoraextra_set.all %}
                <li class="list-group-item">

                <a href="{% url 'edit_hora_extra' rhe.id %}">{{ rhe.motivo }}</a>
                    <p>{{ rhe.horaextra }}   </p>
                </li>
            {% endfor %}
        </ul>
        <a class="btn btn-info" href="{% url 'create_hora_extra' %}"> Add Hora Extra</a>
        <h3>Total de horas extra: {{ object.total_hora_extra }}</h3>

    </div>
{% endif %}


{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base/base.html' %}

{% block title %}
    Lista de Funcionários
{% endblock %}

{% block main %}
    List

    {% for funcionario in object_list %}
        <p>
            <a href="{% url 'edit_funcionarios' funcionario.id %}">{{ funcionario }}</a>
        </p>

        <p>
            <a href="{% url 'delete_funcionarios' funcionario.id %}">Deletar</a>
        </p>

    {% endfor %}

    <div class="col-sm">
        <a href="{% url 'create_funcionarios' %}" class="btn btn-info"> Novo </a>
        <a class="btn btn-secondary" href="{% url 'pdf-reportlab' %}"> Relatório de funcionários (report-lab) </a>
        <a class="btn btn-outline-dark" href="{% url 'pdf-xtml2pdf' %}"> Relatório de funcionários (xhtml2pdf) </a>
        <a class="btn btn-danger" href="{% url 'pdf-xtml2pdf-debug' %}"> Relatório de funcionários (xhtml2pdf template) </a>
    </div>



{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base/base.html' %}

{% load bootstrap %}
{% load static %}

{% block css %}
    <style>
        .teste { color: red; }
    </style>
{% endblock %}

{% block title %}
    Relatório xtml2pdf
{% endblock %}

{% block main %}
    <h1 class="teste"> Meu Relatório </h1>
    <p class="btn btn-secondary"> {{ vendas }}</p>

{% load plotly_dash %}

<br>
<h1> Plotagem </h1>

<div class="{% plotly_class name='SimpleExample' %} card" style="height: 50%; width: 50%">
    {% plotly_app name='SimpleExample' ratio=1 %}
</div>
<br>

{% endblock %}